labkeeper/labkeeper/urls.py
from django.conf.urls import patterns, include, static, url
from django.contrib import admin
import settings


admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', 'labkeeper.views.home', name='home'),

    # Native apps
    url(r'^forum/', include('forum.urls')),
    url(r'^labs/', include('labs.urls')),
    url(r'^reservations/', include('scheduler.urls')),
    url(r'^users/', include('users.urls')),

    # CKEditor
    url(r'^ckeditor/', include('ckeditor.urls')),

    # Admin interface
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += static.static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

labkeeper/labs/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('labs',
    # Lab list
    url(r'^$', 'views.default', name='labs'),

    # Lab creation
    url(r'^new/$', 'views.create_lab', name='labs_create_lab'),

    # Lab info
    url(r'^(?P<lab_id>\d+)/$', 'views.lab', name='labs_lab'),
    url(r'^(?P<lab_id>\d+)/schedule/$', 'views.schedule', name='labs_schedule'),
    url(r'^(?P<lab_id>\d+)/members/$', 'views.member_list', name='labs_member_list'),
    url(r'^(?P<lab_id>\d+)/activity/$', 'views.recent_activity', name='labs_recent_activity'),

    # Lab/device management
    url(r'^(?P<lab_id>\d+)/edit/$', 'views.edit_lab_profile', name='labs_edit_lab_profile'),
    url(r'^(?P<lab_id>\d+)/settings/$', 'views.edit_lab_settings', name='labs_edit_lab_settings'),
    url(r'^(?P<lab_id>\d+)/manage/topologies/$', 'views.manage_topologies', name='labs_manage_topologies'),
    url(r'^(?P<lab_id>\d+)/manage/devices/$', 'views.manage_devices', name='labs_manage_devices'),
    url(r'^(?P<lab_id>\d+)/manage/pods/$', 'views.manage_pods', name='labs_manage_pods'),
    url(r'^(?P<lab_id>\d+)/manage/consoleservers/$', 'views.manage_consoleservers', name='labs_manage_consoleservers'),
    url(r'^(?P<lab_id>\d+)/delete/$', 'views.delete_lab', name='labs_delete_lab'),
    url(r'^topologies/(?P<topology_id>\d+)/delete/$', 'views.delete_topology', name='labs_delete_topology'),
    url(r'^pods/(?P<pod_id>\d+)/edit/$', 'views.edit_pod', name='labs_edit_pod'),
    url(r'^pods/(?P<pod_id>\d+)/delete/$', 'views.delete_pod', name='labs_delete_pod'),
    url(r'^consoleservers/(?P<cs_id>\d+)/edit/$', 'views.edit_consoleserver', name='labs_edit_consoleserver'),
    url(r'^consoleservers/(?P<cs_id>\d+)/delete/$', 'views.delete_consoleserver', name='labs_delete_consoleserver'),
    url(r'^devices/(?P<device_id>\d+)/edit/$', 'views.edit_device', name='labs_edit_device'),
    url(r'^devices/(?P<device_id>\d+)/delete/$', 'views.delete_device', name='labs_delete_device'),

    # Membership invitations
    url(r'^invitations/(?P<invitation_id>\d+)/(?P<response>accept|decline)/$', 'views.invitation_response', name='labs_invitation_response'),

)

labkeeper/users/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('users',
    #url(r'^$', 'views.default', name='users'),

    # Login/logout
    url(r'^login/$', 'views.login', name='users_login'),
    url(r'^logout/$', 'views.logout', name='users_logout'),

    # User profiles
    url(r'^(?P<username>\w+)/$', 'views.profile', name='users_profile'),
    url(r'^(?P<username>\w+)/edit/$', 'views.edit_profile', name='users_edit_profile'),
)

labkeeper/users/models.py
import pytz

from django.db import models
from django.db.models.signals import post_save
from django.conf import settings
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone

from django_countries import CountryField

GENDER_CHOICES = (
    (0, 'Male'),
    (1, 'Female'),
)

TIMEZONE_CHOICES = [(tz, timezone.now().astimezone(pytz.timezone(tz)).strftime("[UTC%z] {0}".format(name)))
                    for tz, name in settings.SUPPORTED_TIMEZONES.items()]

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile', editable=False)
    last_active = models.DateTimeField('Last active', blank=True, null=True, editable=False)
    birth_date = models.DateField('Birth date', blank=True, null=True)
    gender = models.PositiveSmallIntegerField('Gender', choices=GENDER_CHOICES, blank=True, null=True)
    country = CountryField(blank=True)
    timezone = models.CharField('Timezone', max_length=40, choices=TIMEZONE_CHOICES, default='UTC')
    location = models.CharField('Location', max_length=50, blank=True)
    twitter = models.CharField('Twitter', max_length=15, blank=True)
    facebook = models.CharField('Facebook', max_length=50, blank=True)

    class Meta:
        pass

    def __unicode__(self):
        return "Profile for {0}".format(self.user.username)

    def get_absolute_url(self):
        return reverse('users_profile', kwargs={'username': self.user.username})

def create_profile_for_user(instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
post_save.connect(create_profile_for_user, sender=User)

labkeeper/users/forms.py
from django import forms

from users.models import UserProfile


class UserProfileForm(forms.ModelForm):

    username = forms.RegexField(regex=r'^\w+$', max_length=30)
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    email = forms.EmailField(label='Email address')
    password1 = forms.CharField(required=False, widget=forms.PasswordInput, label='Password')
    password2 = forms.CharField(required=False, widget=forms.PasswordInput, label='Password (confirm)')

    class Meta:
        model = UserProfile
        fields = ['username', 'first_name', 'last_name', 'email', 'birth_date', 'gender',
                  'country', 'timezone', 'location',
                  'twitter', 'facebook',
                  'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        self.fields['username'].initial = self.instance.user.username
        self.fields['first_name'].initial = self.instance.user.first_name
        self.fields['last_name'].initial = self.instance.user.last_name
        self.fields['email'].initial = self.instance.user.email

    def save(self, *args, **kwargs):

        # Save User attributes
        u = self.instance.user
        u.username = self.cleaned_data['username']
        u.first_name = self.cleaned_data['first_name']
        u.last_name = self.cleaned_data['last_name']
        u.email = self.cleaned_data['email']
        if self.cleaned_data['password1']:
            u.set_password(self.cleaned_data['password1'])
        u.save()

        return super(UserProfileForm, self).save(*args,**kwargs)

    def clean(self):
        cleaned_data = super(UserProfileForm, self).clean()

        if cleaned_data.get('password1') or cleaned_data.get('password2'):
            if cleaned_data.get('password1') != cleaned_data.get('password2'):
                msg = 'Password must be repeated twice for verification'
                self._errors['password1'] = self.error_class([msg])
                self._errors['password2'] = self.error_class([msg])

        return cleaned_data

labkeeper/users/views.py
import pytz

from django.contrib import messages
from django.contrib.auth import login as auth_login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.http import HttpResponseForbidden, HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render

from users.forms import UserProfileForm


def login(request):

    redirect_to = request.GET.get('next', '')
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():

            # Log the user in and set his preferred timezone
            auth_login(request, form.get_user())
            request.session['django_timezone'] = pytz.timezone(form.get_user().profile.timezone)

            messages.success(request, "Welcome {0}! You are logged in.".format(request.user))
            if not redirect_to.strip() or '//' in redirect_to:
                return redirect(reverse('home'))
            else:
                return HttpResponseRedirect(redirect_to)
    else:
        form = AuthenticationForm(request)
        request.session.set_test_cookie()

    return render(request, 'users/login.html', {
        'form': form,
        'next': redirect_to,
        })


def logout(request):

    auth_logout(request)

    messages.info(request, "You have logged out.")
    return redirect(reverse('users_login'))


def profile(request, username):

    user = get_object_or_404(User, username=username)

    return render(request, 'users/profile.html', {
        'profile': user.profile,
        })


def edit_profile(request, username):

    user = get_object_or_404(User, username=username)
    if request.user != user:
        return HttpResponseForbidden()

    # Processing a submitted form
    if request.method == 'POST':
        form = UserProfileForm(request.POST, instance=user.profile)
        if form.is_valid():
            form.save()
            request.session['django_timezone'] = pytz.timezone(form.cleaned_data['timezone'])
            messages.success(request, "Your profile has been updated.")
            return redirect(reverse('users_profile', kwargs={'username': user.username}))
    else:
        form = UserProfileForm(instance=user.profile)

    return render(request, 'users/edit_profile.html', {
        'profile': user.profile,
        'form': form,
        })

labkeeper/templates/users/edit_profile.html
{% extends '_base.html' %}
{% load bootstrap_toolkit %}

{% block content %}
<form class="form-horizontal" action="." method="post">
  <fieldset>
    <legend>Profile</legend>
    {% csrf_token %}
    {{ form|as_bootstrap }}
  </fieldset>
  <div class="form-actions">
    <a href="{{ profile.get_absolute_url }}" class="btn">Go back</a>
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
</form>
{% endblock %}

labkeeper/templates/users/login.html
{% extends '_base.html' %}
{% load bootstrap_toolkit %}

{% block content %}
<div class="row">
  <div class="span6 offset3">
    <form class="form-horizontal" action="{% url 'users_login' %}?next={{ next }}" method="post">
      <fieldset>
        <legend>Log in</legend>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        {{ form|as_bootstrap }}
      </fieldset>
      <div class="form-actions">
        <button type="submit" class="btn btn-primary">Log in</button>
      </div>
    </form>
  </div>
</div>
{% endblock %}

labkeeper/templates/users/profile.html
{% extends '_base.html' %}

{% block title %}{{ block.super }} - {{ profile.user }}{% endblock %}

{% block content %}
<h2>{{ profile.user }}{% ifequal profile.user request.user %} <small><a href="{% url 'users_edit_profile' profile.user.username %}">edit</a></small>{% endifequal %}</h2>
<div class="row">
  <div class="span7">
    <div class="row-fluid">
      <div class="span3 muted">Name</div>
      <div class="span9">{{ profile.user.first_name }} {{ profile.user.last_name }}</div>
    </div>
    <div class="row-fluid">
      <div class="span3 muted">Date joined</div>
      <div class="span9">{{ profile.user.date_joined|date }}</div>
    </div>
    <div class="row-fluid">
      <div class="span3 muted">Last active</div>
      <div class="span9">{% if profile.last_active %}{{ profile.last_active }}{% else %}Never{% endif %}</div>
    </div>
    {% ifequal profile.user request.user %}
    <div class="row-fluid">
      <div class="span3 muted">Email</div>
      <div class="span9">{{ profile.user.email }} <span class="label label-info">private</span></div>
    </div>
    {% endifequal %}
    <div class="row-fluid">
      <div class="span3 muted">Country</div>
      <div class="span9">{{ profile.country.name }}</div>
    </div>
    <div class="row-fluid">
      <div class="span3 muted">Location</div>
      <div class="span9">{{ profile.location }}</div>
    </div>
    <div class="row-fluid">
      <div class="span3 muted">Time zone</div>
      <div class="span9">{{ profile.get_timezone_display }}</div>
    </div>
    {% if profile.twitter %}
    <div class="row-fluid">
      <div class="span3 muted">Twitter</div>
      <div class="span9"><a href="http://twitter.com/{{ profile.twitter }}">@{{ profile.twitter }}</a></div>
    </div>
    {% endif %}
    {% if profile.facebook %}
    <div class="row-fluid">
      <div class="span3 muted">Facebook</div>
      <div class="span9"><a href="http://facebook.com/{{ profile.facebook }}">{{ profile.facebook }}</a></div>
    </div>
    {% endif %}
  </div>
  <div class="span5">
    {% ifequal request.user profile.user %}
    {% with profile.user.membership_invitations.all as invitations %}
    {% if invitations %}
    <h4>Invitations</h4>
    <ul>
      {% for i in invitations %}<li>{{ i.sender }} invited you to <a href="{{ i.lab.get_absolute_url }}">{{ i.lab }}</a><br />
      <a href="{% url 'labs_invitation_response' i.id 'accept' %}" class="btn btn-mini btn-success">Accept</a>
      <a href="{% url 'labs_invitation_response' i.id 'decline' %}" class="btn btn-mini btn-danger" onclick="return confirm('Decline the invitation to {{ i.lab }}?')">Decline</a></li>{% endfor %}
    </ul>
    {% endif %}
    {% endwith %}
    {% endifequal %}
    <h4>Memberships</h4>
    <ul>
      {% for m in profile.user.memberships.all %}<li>{% if not m.lab.is_public %}<i class="icon-lock"></i> {% endif %}<a href="{{ m.lab.get_absolute_url }}">{{ m.lab }}</a> ({{ m.get_role_display }})</li>
      {% empty %}<li>None yet</li>
      {% endfor %}
    </ul>
    <h4>Upcoming Reservations</h4>
    <ul>
      {% for r in profile.user.reservations.upcoming %}<li><a href="{{ r.get_absolute_url }}">{{ r.lab }} - {{ r.start_time }}</a></li>
      {% empty %}<li>No upcoming reservations</li>
      {% endfor %}
    </ul>
  </div>
</div>
{% endblock %}